@startuml

producer -> producer: determine topic and partition name and producer unique id
producer -> producer: accumulate batch of messages
producer -> producer: get num of minute periods since epoch (or whatever time period)
producer -> storage: create object named "topic name / partition name / time period / producer id"
producer -> storage: upload file of events to "topic name / partition name / time period / producer id"


@enduml